# Generated by Django 3.1.3 on 2020-11-08 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('last_check', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BarSocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=100, null=True, unique=True)),
                ('username', models.CharField(max_length=30)),
                ('user_reference', models.CharField(blank=True, max_length=30, null=True)),
                ('bar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bars.bar')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(max_length=1000)),
                ('url', models.URLField()),
                ('bar_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bars.barsocialmedia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bars.post')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='barsocialmedia',
            name='social_media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bars.socialmedia'),
        ),
        migrations.AddField(
            model_name='bar',
            name='social_medias',
            field=models.ManyToManyField(through='bars.BarSocialMedia', to='bars.SocialMedia'),
        ),
    ]
